name: e2e slsa-verifier

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Run daily as a dry-run/test.
  schedule:
    - cron: "0 1 * * *"

jobs:
  verify-attestations:
    strategy:
      matrix:
        slsa-verifier-verision: [
          latest,
          v2.6.0,
        ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: 1.21

      - name: Install slsa-verifier
        run: go install github.com/slsa-framework/slsa-verifier/v2/cli/slsa-verifier@${{ matrix.slsa-verifier-verision }}

      - name: Verify attestations
        run: |
          ./.github/workflows/scripts/verify-all.sh
